---
title: "Ycombinator's conversion rate"
output: html_notebook
---

```{r, echo=FALSE, message=FALSE}
Sys.setenv(TZ='GMT')
library(rvest)
library(dplyr)
library(readr)
library(survival)
```

```{r}
site <- read_html("http://yclist.com/")
```

```{r}
extract <- function(data, xpath) {
  data %>%
    html_nodes(xpath = xpath) %>%
    html_text()
}
companies <- tibble::tibble(
  company = site %>% extract(
    "//td[(((count(preceding-sibling::*) + 1) = 2) and parent::*)]"),
  batch = site %>% extract(
    "//td[(((count(preceding-sibling::*) + 1) = 4) and parent::*)]") %>%
    gsub("\n", "", .) %>%
    gsub(" ", "", .),
  status = site %>% extract(
    "//td[(((count(preceding-sibling::*) + 1) = 5) and parent::*)]")
)
```

```{r}
start_date <- function(batch) {
  if(!grepl("W", batch) & !grepl("S", batch)) return(NA)
  month <- ifelse(grepl("W", batch), "01", "06")
  year <- batch %>% gsub("W", "", .) %>%
    gsub("S", "", .) %>%
    paste0("20", .)
  paste0(year, "-", month, "-01") %>%
    as.POSIXct(origin = "1970-01-01", tz = "UTC")
}
```

```{r}
# companies %>%
#   mutate(start = as.POSIXct(Vectorize(start_date)(batch), origin = "1970-01-01")) %>%
#   filter(status == "Exited") %>%
#   select(company) %>%
#   write.csv("exits.csv", row.names = FALSE)
```

```{r}
companies %>%
  mutate(start = as.POSIXct(Vectorize(start_date)(batch), origin = "1970-01-01")) %>%
  filter(!grepl("F", batch)) %>%
  left_join(
    read.csv("exits.csv", stringsAsFactors = FALSE) %>% tbl_df(),
    by = "company"
  ) %>%
  mutate(time = ifelse(
    is.na(exit), difftime(Sys.time(), start, units = "days"),
    difftime(exit, start, units = "days")),
    censor = ifelse(!is.na(exit) | status == "Exited", 1, 0)
  ) %>%
  survfit(Surv(time, censor) ~ 1, data = .) %>%
  plot(fun = "event", xscale=365.25)
```
